env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - standard
  - airbnb
  - plugin:import/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always

